FROM gitlab.pea.co.th:443/developer/vms-plus/api/dependency_proxy/containers/golang:1.24-alpine

WORKDIR /app

RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod .

COPY go.sum .

RUN go mod download

USER 65532