// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/booking-admin-dept/request/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint fetches details of a specific booking request using its unique identifier (TrnRequestUID).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Retrieve a specific booking request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrnRequestUID (trn_request_uid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/search-requests": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "Search for requests using a keyword and get the summary of counts grouped by request status code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Search booking requests and get summary counts by request status code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword (matches request_no, vehicle_license_plate, vehicle_user_emp_name, or work_place)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by multiple request status codes (comma-separated, e.g., 'A,B,C')",
                        "name": "ref_request_status_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by start datetime (YYYY-MM-DD format)",
                        "name": "startdate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by end datetime (YYYY-MM-DD format)",
                        "name": "enddate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order by request_no, start_datetime, ref_request_status_code",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order direction: asc or desc",
                        "name": "order_dir",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page (default: 10)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-approved": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the sended back status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update Approved status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Approved data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Approved"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-canceled": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the cancel status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update cancel status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Canceled data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Canceled"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-cost": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the cost information for an existing booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update cost details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-document": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the document associated with their booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update document details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-driver": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the cost information for an existing booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update driver for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-pickup": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the pickup information for an existing booking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update pickup details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Pickup data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Pickup"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-sended-back": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the sended back status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update sended back status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_SendedBack data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_SendedBack"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-trip": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the details of an existing trip associated with their request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update trip details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Trip data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Trip"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-vehicle": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the cost information for an existing booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update vehicle for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin-dept/update-vehicle-user": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the vehicle details associated with their request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin-dept"
                ],
                "summary": "Update vehicle information for a booking user",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_VehicleUser data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_VehicleUser"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/request/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint fetches details of a specific booking request using its unique identifier (TrnRequestUID).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Retrieve a specific booking request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrnRequestUID (trn_request_uid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/search-requests": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "Search for requests using a keyword and get the summary of counts grouped by request status code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Search booking requests and get summary counts by request status code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword (matches request_no, vehicle_license_plate, vehicle_user_emp_name, or work_place)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by multiple request status codes (comma-separated, e.g., 'A,B,C')",
                        "name": "ref_request_status_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by start datetime (YYYY-MM-DD format)",
                        "name": "startdate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by end datetime (YYYY-MM-DD format)",
                        "name": "enddate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order by request_no, start_datetime, ref_request_status_code",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order direction: asc or desc",
                        "name": "order_dir",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page (default: 10)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-approved": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the sended back status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update Approved status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Approved data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Approved"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-canceled": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the cancel status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update cancel status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Canceled data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Canceled"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-cost": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the cost information for an existing booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update cost details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-document": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the document associated with their booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update document details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-driver": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the cost information for an existing booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update driver for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-pickup": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the pickup information for an existing booking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update pickup details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Pickup data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Pickup"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-sended-back": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the sended back status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update sended back status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_SendedBack data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_SendedBack"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-trip": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the details of an existing trip associated with their request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update trip details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Trip data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Trip"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-vehicle": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the cost information for an existing booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update vehicle for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-admin/update-vehicle-user": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the vehicle details associated with their request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-admin"
                ],
                "summary": "Update vehicle information for a booking user",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_VehicleUser data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_VehicleUser"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-approver/request/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint fetches details of a specific booking request using its unique identifier (TrnRequestUID).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-approver"
                ],
                "summary": "Retrieve a specific booking request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrnRequestUID (trn_request_uid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-approver/search-requests": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "Search for requests using a keyword and get the summary of counts grouped by request status code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-approver"
                ],
                "summary": "Search booking requests and get summary counts by request status code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword (matches request_no, vehicle_license_plate, vehicle_user_emp_name, or work_place)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by multiple request status codes (comma-separated, e.g., 'A,B,C')",
                        "name": "ref_request_status_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by start datetime (YYYY-MM-DD format)",
                        "name": "startdate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by end datetime (YYYY-MM-DD format)",
                        "name": "enddate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order by request_no, start_datetime, ref_request_status_code",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order direction: asc or desc",
                        "name": "order_dir",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page (default: 10)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-approver/update-approved": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the sended back status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-approver"
                ],
                "summary": "Update sended back status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Approved data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Approved"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-approver/update-canceled": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the cancel status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-approver"
                ],
                "summary": "Update cancel status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Canceled data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Canceled"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-approver/update-sended-back": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the sended back status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-approver"
                ],
                "summary": "Update sended back status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_SendedBack data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_SendedBack"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-final/request/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint fetches details of a specific booking request using its unique identifier (TrnRequestUID).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-final"
                ],
                "summary": "Retrieve a specific booking request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrnRequestUID (trn_request_uid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-final/search-requests": {
            "get": {
                "description": "Search for requests using a keyword and get the summary of counts grouped by request status code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-final"
                ],
                "summary": "Search booking requests and get summary counts by request status code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword (matches request_no, vehicle_license_plate, vehicle_user_emp_name, or work_place)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by multiple request status codes (comma-separated, e.g., 'A,B,C')",
                        "name": "ref_request_status_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by start datetime (YYYY-MM-DD format)",
                        "name": "startdate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by end datetime (YYYY-MM-DD format)",
                        "name": "enddate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order by request_no, start_datetime, ref_request_status_code",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order direction: asc or desc",
                        "name": "order_dir",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page (default: 10)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-final/update-approved": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the sended back status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-final"
                ],
                "summary": "Update sended back status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Approved data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Approved"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-final/update-canceled": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the cancel status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-final"
                ],
                "summary": "Update cancel status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Canceled data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Canceled"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-final/update-sended-back": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the sended back status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-final"
                ],
                "summary": "Update sended back status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_SendedBack data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_SendedBack"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/create-request": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to create a new request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Create a new booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Request data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Request"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/request/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint fetches details of a specific booking request using its unique identifier (TrnRequestUID).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Retrieve a specific booking request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "TrnRequestUID (trn_request_uid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/requests": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint retrieves a list of booking requests for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Get a list of booking requests",
                "responses": {}
            }
        },
        "/api/booking-user/search-requests": {
            "get": {
                "description": "Search for requests using a keyword and get the summary of counts grouped by request status code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Search booking requests and get summary counts by request status code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search keyword (matches request_no, vehicle_license_plate, vehicle_user_emp_name, or work_place)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by multiple request status codes (comma-separated, e.g., 'A,B,C')",
                        "name": "ref_request_status_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by start datetime (YYYY-MM-DD format)",
                        "name": "startdate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by end datetime (YYYY-MM-DD format)",
                        "name": "enddate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order by request_no, start_datetime, ref_request_status_code",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order direction: asc or desc",
                        "name": "order_dir",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/update-approved": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the approval status of their booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Update approval status for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Approver data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Approver"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/update-canceled": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the cancel status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Update cancel status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Canceled data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Canceled"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/update-cost": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the cost information for an existing booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Update cost details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/update-document": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the document associated with their booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Update document details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Document data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Document"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/update-pickup": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the pickup information for an existing booking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Update pickup details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Pickup data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Pickup"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/update-sended-back": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows users to update the sended back status of an item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Update sended back status for an item",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_SendedBack data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_SendedBack"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/update-trip": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the details of an existing trip associated with their request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Update trip details for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_Trip data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_Trip"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/update-vehicle-type": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the vehicle type associated with their booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Update vehicle type for a booking request",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_VehicleType data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_VehicleType"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/booking-user/update-vehicle-user": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to update the vehicle details associated with their request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Booking-user"
                ],
                "summary": "Update vehicle information for a booking user",
                "parameters": [
                    {
                        "description": "VmsTrnRequest_Update_VehicleUser data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VmsTrnRequest_Update_VehicleUser"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/driver/search": {
            "get": {
                "description": "Get a list of drivers filtered by name with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Drivers"
                ],
                "summary": "Get drivers by name with pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driver name to search",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/log/request/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Log"
                ],
                "summary": "Get log requests by trnRequestUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction Request UID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/login/authen-keycloak": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint authenticates a user using Keycloak, providing secure access to protected resources.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Authenticate user via Keycloak",
                "parameters": [
                    {
                        "description": "KeyCloak_Authen data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KeyCloak_Authen"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/login/authen-thaiid": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint authenticates a user using ThaiID, providing secure access to protected resources.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Authenticate user via ThaiID",
                "parameters": [
                    {
                        "description": "ThaiID_Authen data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ThaiID_Authen"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/login/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint retrieves a user profile for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Get user profile",
                "responses": {}
            }
        },
        "/api/login/refresh-token": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows a user to refresh their authentication token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Refresh authentication token",
                "parameters": [
                    {
                        "description": "RefreshToken_Request data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RefreshToken_Request"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/login/request-keycloak": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows a user to request an authentication token from Keycloak for secure access.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Request Keycloak authentication token",
                "parameters": [
                    {
                        "description": "KeyCloak_Request data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KeyCloak_Request"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/login/request-otp": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows a user to request a One-Time Password (OTP) for authentication purposes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Request One-Time Password (OTP) for user authentication",
                "parameters": [
                    {
                        "description": "OTP_Request data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OTP_Request"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/login/request-thaiid": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows a user to request an authentication token from ThaiID for secure access.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Request ThaiID authentication token",
                "parameters": [
                    {
                        "description": "ThaiID_Request data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ThaiID_Request"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/login/verify-otp": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint allows a user to verify the One-Time Password (OTP) they received.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Verify One-Time Password (OTP) for user authentication",
                "parameters": [
                    {
                        "description": "OTPVerify_Request data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OTPVerify_Request"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/logout": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a user to log out of their session, invalidating their authentication token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Log out the current user",
                "responses": {}
            }
        },
        "/api/ref/cost-type": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a user to retrieve a list of available cost types for booking requests.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "REF"
                ],
                "summary": "Retrieve available cost types",
                "responses": {}
            }
        },
        "/api/ref/request-status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a booking user to retrieve the status of their booking requests.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "REF"
                ],
                "summary": "Retrieve the status of booking requests",
                "responses": {}
            }
        },
        "/api/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Upload a file to the server and save it in D:\\uploads",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uploads"
                ],
                "summary": "Uploads a file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully uploaded file",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid file",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/vehicle/category": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "Fetches vehicle categories with optional filtering and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicle"
                ],
                "summary": "Get vehicle categories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/vehicle/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "Retrieves vehicles based on search text, department, and car type filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicle"
                ],
                "summary": "Search vehicles by brand, license plate, and filters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search text (Vehicle Brand Name or License Plate)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by icle Owner Department",
                        "name": "vehicle_owner_dept",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by Car Type",
                        "name": "car_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by Vehicle Category Code",
                        "name": "category_code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/vehicle/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "AuthorizationAuth": []
                    }
                ],
                "description": "This endpoint allows a user to retrieve the details of a specific vehicle associated with a booking request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vehicle"
                ],
                "summary": "Retrieve details of a specific vehicle",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle ID (mas_vehicle_uid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.KeyCloak_Authen": {
            "type": "object",
            "required": [
                "code",
                "redirect_uri"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "b7d287b3-8ded-40f2-9060-a60f1207b378.6c99a927-ae7f-4d15-a69c-ea8aed9b612f.88e696e4-d20f-47f5-a391-26854ff28848"
                },
                "redirect_uri": {
                    "type": "string",
                    "example": "http://localhost/callback_code_token"
                }
            }
        },
        "models.KeyCloak_Request": {
            "type": "object",
            "required": [
                "redirect_uri"
            ],
            "properties": {
                "redirect_uri": {
                    "type": "string",
                    "example": "http://localhost/callback_code_token"
                }
            }
        },
        "models.OTPVerify_Request": {
            "type": "object",
            "required": [
                "otp",
                "otpId"
            ],
            "properties": {
                "otp": {
                    "type": "string",
                    "example": "000000"
                },
                "otpId": {
                    "type": "string",
                    "example": "35801ccf-43cc-4e21-ae23-fc40471d9789"
                }
            }
        },
        "models.OTP_Request": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "phone": {
                    "type": "string",
                    "example": "0818088770"
                }
            }
        },
        "models.RefreshToken_Request": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "models.ThaiID_Authen": {
            "type": "object",
            "required": [
                "code",
                "redirect_uri"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "b7d287b3-8ded-40f2-9060-a60f1207b378.6c99a927-ae7f-4d15-a69c-ea8aed9b612f.88e696e4-d20f-47f5-a391-26854ff28848"
                },
                "redirect_uri": {
                    "type": "string",
                    "example": "http://localhost/callback_code_token"
                }
            }
        },
        "models.ThaiID_Request": {
            "type": "object",
            "required": [
                "redirect_uri"
            ],
            "properties": {
                "redirect_uri": {
                    "type": "string",
                    "example": "http://localhost/callback_code_token"
                }
            }
        },
        "models.VmsTrnRequest_Approved": {
            "type": "object",
            "properties": {
                "trn_request_uid": {
                    "type": "string",
                    "example": "a7de5318-1e05-4511-abe7-8c1c6374ab29"
                }
            }
        },
        "models.VmsTrnRequest_Canceled": {
            "type": "object",
            "properties": {
                "canceled_request_reason": {
                    "type": "string",
                    "example": "Test Cancel"
                },
                "trn_request_uid": {
                    "type": "string",
                    "example": "a7de5318-1e05-4511-abe7-8c1c6374ab29"
                }
            }
        },
        "models.VmsTrnRequest_Request": {
            "type": "object",
            "properties": {
                "attached_document": {
                    "type": "string",
                    "example": "document.pdf"
                },
                "car_user_internal_contact_number": {
                    "type": "string",
                    "example": "1234567890"
                },
                "car_user_mobile_contact_number": {
                    "type": "string",
                    "example": "0987654321"
                },
                "cost_no": {
                    "type": "string",
                    "example": "COST2024001"
                },
                "end_datetime": {
                    "type": "string",
                    "example": "2025-01-01T10:00:00Z"
                },
                "is_admin_choose_driver": {
                    "type": "string",
                    "example": "0"
                },
                "is_admin_choose_vehicle": {
                    "type": "string",
                    "example": "0"
                },
                "is_driver_need": {
                    "description": "Step 3",
                    "type": "string",
                    "example": "1"
                },
                "is_have_sub_request": {
                    "type": "string",
                    "example": "1"
                },
                "is_pea_employee_driver": {
                    "type": "string",
                    "example": "1"
                },
                "mas_carpool_driver_uid": {
                    "type": "string",
                    "example": "a6c8a34b-9245-49c8-a12b-45fae77a4e7d"
                },
                "mas_vehicle_uid": {
                    "description": "Step 2",
                    "type": "string",
                    "example": "389b0f63-4195-4ece-bf35-0011c2f5f28c"
                },
                "number_of_passengers": {
                    "type": "integer",
                    "example": 3
                },
                "objective": {
                    "type": "string",
                    "example": "Business Meeting"
                },
                "pickup_datetime": {
                    "type": "string",
                    "example": "2025-02-16T08:30:00Z"
                },
                "pickup_place": {
                    "type": "string",
                    "example": "Main Office"
                },
                "ref_cost_type_code": {
                    "type": "integer",
                    "example": 101
                },
                "ref_request_type_code": {
                    "type": "integer",
                    "example": 1
                },
                "reference_number": {
                    "type": "string",
                    "example": "REF123456"
                },
                "remark": {
                    "type": "string",
                    "example": "Urgent request"
                },
                "requested_vehicle_type_id": {
                    "type": "integer",
                    "example": 1
                },
                "reserved_time_type": {
                    "type": "string",
                    "example": "1"
                },
                "start_datetime": {
                    "type": "string",
                    "example": "2025-01-01T08:00:00Z"
                },
                "trip_type": {
                    "type": "integer",
                    "example": 1
                },
                "vehicle_user_dept_sap": {
                    "type": "string",
                    "example": "DPT001"
                },
                "vehicle_user_emp_id": {
                    "description": "Step1",
                    "type": "string",
                    "example": "E12345"
                },
                "vehicle_user_emp_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "work_place": {
                    "type": "string",
                    "example": "Head Office"
                }
            }
        },
        "models.VmsTrnRequest_SendedBack": {
            "type": "object",
            "properties": {
                "sended_back_request_reason": {
                    "type": "string",
                    "example": "Test Send Back"
                },
                "trn_request_uid": {
                    "type": "string",
                    "example": "a7de5318-1e05-4511-abe7-8c1c6374ab29"
                }
            }
        },
        "models.VmsTrnRequest_Update_Approver": {
            "type": "object",
            "properties": {
                "approved_request_emp_id": {
                    "type": "string",
                    "example": "700002"
                },
                "trn_request_uid": {
                    "type": "string",
                    "example": "a7de5318-1e05-4511-abe7-8c1c6374ab29"
                }
            }
        },
        "models.VmsTrnRequest_Update_Document": {
            "type": "object",
            "properties": {
                "attached_document": {
                    "type": "string",
                    "example": "document.pdf"
                },
                "reference_number": {
                    "type": "string",
                    "example": "REF123456"
                },
                "trn_request_uid": {
                    "type": "string",
                    "example": "a7de5318-1e05-4511-abe7-8c1c6374ab29"
                }
            }
        },
        "models.VmsTrnRequest_Update_Pickup": {
            "type": "object",
            "properties": {
                "pickup_datetime": {
                    "type": "string",
                    "example": "2025-02-16T08:00:00Z"
                },
                "pickup_place": {
                    "type": "string",
                    "example": "Main Office"
                },
                "trn_request_uid": {
                    "type": "string",
                    "example": "a7de5318-1e05-4511-abe7-8c1c6374ab29"
                }
            }
        },
        "models.VmsTrnRequest_Update_Trip": {
            "type": "object",
            "properties": {
                "end_datetime": {
                    "type": "string",
                    "example": "2025-01-01T10:00:00Z"
                },
                "number_of_passengers": {
                    "type": "integer",
                    "example": 3
                },
                "objective": {
                    "type": "string",
                    "example": "Business Meeting"
                },
                "reserved_time_type": {
                    "type": "string",
                    "example": "1"
                },
                "start_datetime": {
                    "type": "string",
                    "example": "2025-01-01T08:00:00Z"
                },
                "trip_type": {
                    "type": "integer",
                    "example": 1
                },
                "trn_request_uid": {
                    "type": "string",
                    "example": "a7de5318-1e05-4511-abe7-8c1c6374ab29"
                },
                "work_place": {
                    "type": "string",
                    "example": "Head Office"
                }
            }
        },
        "models.VmsTrnRequest_Update_VehicleType": {
            "type": "object",
            "properties": {
                "requested_vehicle_type_id": {
                    "type": "integer",
                    "example": 1
                },
                "trn_request_uid": {
                    "type": "string",
                    "example": "a7de5318-1e05-4511-abe7-8c1c6374ab29"
                }
            }
        },
        "models.VmsTrnRequest_Update_VehicleUser": {
            "type": "object",
            "properties": {
                "car_user_internal_contact_number": {
                    "type": "string",
                    "example": "1234567890"
                },
                "car_user_mobile_contact_number": {
                    "type": "string",
                    "example": "0987654321"
                },
                "trn_request_uid": {
                    "type": "string",
                    "example": "a7de5318-1e05-4511-abe7-8c1c6374ab29"
                },
                "vehicle_user_dept_sap": {
                    "type": "string",
                    "example": "DPT001"
                },
                "vehicle_user_emp_id": {
                    "type": "string",
                    "example": "700001"
                },
                "vehicle_user_emp_name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-ApiKey",
            "in": "header"
        },
        "AuthorizationAuth": {
            "description": "Bearer [your Authorization]",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "VMS_PLUS",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
